blank_issues_enabled: false
contact_links:
  - name: 公式Discordサーバ
    url: https://discord.gg/zEGrApgGfB
    about: "jao Minecraft Server 自体の運営に関する質問(処罰関連等)はこちらの #support チャンネルにて受け付けます。"
  - name: Javajaotan2 リポジトリ
    url: https://github.com/jaoafa/Javajaotan2
    about: Javajaotan2 についての不具合報告・新機能提案はこちらで受け付けています。
  - name: jaoweb リポジトリ
    url: https://github.com/jaoafa/jaoweb
    about: jao Minecraft Server の Web サイトについての不具合報告・新機能提案はこちらで受け付けています。
  - name: Javajaotan2 リポジトリ
    url: https://github.com/jaoafa/Javajaotan2
    about: Javajaotan2 についての不具合報告・新機能提案はこちらで受け付けています。
